PackageIdentifier: Cellmobs.BNW
PackageVersion: 0.7.10
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bnw-0.7.10-x86_64-pc-windows-msvc\bnw.exe
    PortableCommandAlias: bnw
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cellmobs/bnw-releases/releases/download/v0.7.10/bnw-0.7.10-x86_64-pc-windows-msvc.zip
    InstallerSha256: fa84821e8a4283ca40d95f81c7b464ba7bed76623894142fafba102c18416de6
ManifestType: installer
ManifestVersion: 1.6.0
