PackageIdentifier: Cellmobs.BNW
PackageVersion: 0.7.11
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bnw-0.7.11-x86_64-pc-windows-msvc\bnw.exe
    PortableCommandAlias: bnw
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cellmobs/bnw-releases/releases/download/v0.7.11/bnw-0.7.11-x86_64-pc-windows-msvc.zip
    InstallerSha256: 499ad51907a089866401a507059d9c021eab135f67adf81411fbb93cfc4851b7
ManifestType: installer
ManifestVersion: 1.6.0
